# important features for the pictures
dataset: cifar10
attributes: cifar10
cluster_feature_method: linear # [kmeans, random, linear]
model_type: clip
model_size: ViT-B/32
# model_size: ViT-L/14@336px
mahalanobis: false
division_power: 2
linear_epochs: 200
reinit: true # True/False
num_attributes: 32 # [16, 32, 64, 128, 256, 512]
seed: 1

# optimization parameters
lr: 0.01
batch_size: 4096
epochs: 1000

# model structure
linear_model: [linear, linear] 
score_model: [linear] 