# important features for the pictures
dataset: flower
attributes: flower
cluster_feature_method: linear # [kmeans, random, linear]
model_type: clip
model_size: ViT-B/32
mahalanobis: false
division_power: 2
linear_epochs: 2000
reinit: true # True/False
num_attributes: 128 # [16, 32, 64, 128, 256, 512]
seed: 0

# optimization parameters
lr: 0.001
batch_size: 4096
epochs: -10000

# model structure
linear_model: [linear, linear] 
score_model: [linear]